# Generated by Django 5.2 on 2025-04-13 07:07

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_updated_at_post_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
