# Generated by Django 5.2 on 2025-04-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_alter_post_options_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Attached image', null=True, upload_to='posts_attached_images', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(),
        ),
    ]
