# Generated by Django 5.2 on 2025-04-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_rename_updated_at_comment_edited_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='text_content',
        ),
    ]
