# Generated by Django 5.2 on 2025-04-13 14:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_note_comment_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
