# Generated by Django 5.2 on 2025-04-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_icon',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_icons', verbose_name='Profile Icon'),
        ),
    ]
